services:
  ustreamer:
    image: ghcr.io/eclipse-uprotocol/up-streamer-rust/configurable-streamer:main
    ports:
      - "0.0.0.0:7447:7447"
    expose:
      - "7447"
    volumes:
      - type: bind
        source: ./config
        target: /app/config
    environment:
      - RUST_LOG=debug,zenoh=debug
